### PR TITLE
upgrade to protoc v3.1.0

### PR DESCRIPTION
**Pull request by andrewrothstein**

### CODE REVIEW

**Comment by andrewrothstein** [comment]
I signed it

**Comment by MaerF0x0** [comment]
@murgatroid99   Any chance you can help this along? I'd like to submit a PR for 3.2 as well.

**Comment by markmandel** [comment]
LGTM - @nathanielmanistaatgoogle @nicolasnoble can we merge?

**Comment by nathanielmanistaatgoogle** [comment]
Maybe. I'm not even sure who's in charge of this repository these days; it could be @nicolasnoble or it could be someone else.

**Comment by MaerF0x0** [comment]
@nathanielmanistaatgoogle  , @nicolasnoble  , @markmandel   Do any of you either 1) know who is responsible for this repo or 2) Can find out who is?  

I'd like to do some work on it (particularly updating protoc and golang versions), but dont want to waste my time if it wont get merged.

**Comment by nathanielmanistaatgoogle** [comment]
@dfawley: please review and merge this Go change?

@nicolasnoble, @hsaliak: what's up with this repository? If we don't want to own it, should we delete it? If we do want to own it, should we be better about integrating pull requests?

**Review by dfawley — APPROVED** [review]

**Pull request merged**
